kentonh/gPanel

- general/networking/ip_address.go
- private_server/logging/logging.go
- private_server/routing/routing.go
- public_server/logging/logging.go
- public_server/routing/routing.go
Continued to modulize some of the code. Still needs more work. Also implemented file logging and multiple types of console logging.
> Modulization and Logging

- CONTRIBUTING.md
- ISSUE_TEMPLATE.md
Updated contributing to better document how contributing should work in this project and the issue template just for stylistic purposes.
> Community files

- .gitignore
They create bloat and confusing merge conflicts
> Do not track compiled files in git

- README.md
This is a test within the meeting
> demonstrating git workflow

- CONTRIBUTING.md
- README.md
> updated contributing and readme

- README.md
- main.go
- private_server/logging/logging.go
- private_server/routing/routing.go
- public_server/logging/logging.go
- public_server/routing/routing.go
> updated readme and contribution

- README.md
go get was using https and .git and wasn't working
> fixed go get line

- README.md
Testing the CI, seeing if it works on pull requests to auto-build
> testing CI PR's

- document_roots/webhost/index.html
- pkg/api/authentication.go
- pkg/public/public.go
- pkg/webhost/webhost.go
I removed all of the literals of the status codes and replaced them with their http package constant equivalents (I actually changed some of them which were wrong to point to the right one). I also added some comments to uncommented functions and changed how api responses are handled on the frontend side of things.
> Commenting, removing literals, and API reworking

- pkg/api/user.go
Got it. Don't know why this gave me trouble the night before..
Referencing issue #35
> Check if user already exists in registration process

- pkg/api/README.md
(cherry picked from commit 9c6e90b)
> setup a readme file for api calls #39

- document_roots/webhost/gPanel.html
> sidenav completed

- pkg/api/README.md
- pkg/api/api_handler.go
- pkg/api/user/README.md
- pkg/api/user/auth.go
- pkg/encryption/random_string.go
- pkg/encryption/random_string_test.go
- pkg/public/public.go
- pkg/webhost/authentication.go
- pkg/webhost/webhost.go
Referencing issues #56, #57, and #59
> Issue fixes

- document_roots/webhost/assets/js/panelHandlers/publicServer/maintenance.js
- document_roots/webhost/assets/js/panelHandlers/publicServer/restart.js
- document_roots/webhost/assets/js/panelHandlers/publicServer/shutdown.js
- document_roots/webhost/assets/js/panelHandlers/publicServer/start.js
- document_roots/webhost/assets/js/panelHandlers/publicServer/status.js
- document_roots/webhost/gPanel.html
- document_roots/webhost/index.html
- main.go
- pkg/api/api_handler.go
- pkg/api/server/README.md
- pkg/api/server/maintenance.go
- pkg/api/server/restart.go
- pkg/api/server/server.go
- pkg/api/server/shutdown.go
- pkg/api/server/start.go
- pkg/api/server/status.go
- pkg/api/user/README.md
- pkg/api/user/get_secret.go
- pkg/public/public.go
- pkg/webhost/webhost.go
Turning the server on, off, maintenance mode, and restarting all works now.
> Webhost can now control the public server from the backend

- CONTRIBUTING.md
> remove wiki mentions

- document_roots/webhost/assets/css/style.css
- document_roots/webhost/assets/js/panelHandlers/security/ipFiltering.js
- document_roots/webhost/gPanel.html
> issues #72 and #66 and set up front end for ip filtering

- account/assets/js/panelHandlers/log/view.js
- pkg/api/log/delete.go
- pkg/api/log/read.go
- pkg/file/file.go
- pkg/gpaccount/apihandler.go
- pkg/gpaccount/gpaccount.go
- pkg/public/public.go
I broke it awhile ago but now it is fixed
> fixed logging

- account/gPanel.html
- pkg/api/log/delete.go
- pkg/api/log/read.go
- pkg/file/file.go
- pkg/gpaccount/gpaccount.go
- pkg/gpserver/apihandler.go
- pkg/gpserver/gpserver.go
- pkg/public/public.go
- server/document_root/assets/js/panelHandlers/bundles/manage.js
- server/document_root/assets/js/panelHandlers/bundles/specific/back.js
- server/document_root/assets/js/panelHandlers/bundles/specific/open.js
- server/document_root/assets/js/panelHandlers/log/delete.js
- server/document_root/assets/js/panelHandlers/log/view.js
- server/document_root/gPanel.html
The loggers now have logical names as to what they log and their hooks work inside of the account and server panels.
I have started bundle management creating a modal for specific bundles and passing some data into that modal to keep track of the bundle. APIs now need extended to handle bundles from the server and not just the account. I will be working on that next.
> Logically separated logging, fixed logging hooks in panels, and started bundle management

- pkg/api/server/status.go
- pkg/gpserver/apihandler.go
- pkg/gpserver/gpserver.go
- server/document_root/assets/js/panelHandlers/bundles/specific/open.js
- server/document_root/assets/js/panelHandlers/bundles/specific/server/status.js
- server/document_root/gPanel.html
APIs just need to be configured at this point, a way has been set up to reference specific bundles inside of the request by having the json value "bundle_name" set.
> Account Management from Server gPanel is working

- pkg/gpserver/apihandler.go
- server/document_root/assets/js/panelHandlers/bundles/specific/log/back.js
- server/document_root/assets/js/panelHandlers/bundles/specific/log/view.js
- server/document_root/assets/js/panelHandlers/bundles/specific/server/maintenance.js
- server/document_root/assets/js/panelHandlers/bundles/specific/server/restart.js
- server/document_root/assets/js/panelHandlers/bundles/specific/server/shutdown.js
- server/document_root/assets/js/panelHandlers/bundles/specific/server/start.js
- server/document_root/assets/js/panelHandlers/log/delete.js
- server/document_root/gPanel.html
> Managing bundle public server status and viewing bundle logs from server now works

- pkg/api/bundle/create.go
- pkg/api/log/log.go
- pkg/api/log/read.go
- pkg/api/log/truncate.go
- pkg/file/file.go
- pkg/gpaccount/apihandler.go
- pkg/gpaccount/gpaccount.go
- pkg/gpserver/apihandler.go
- pkg/gpserver/gpserver.go
- pkg/public/public.go
> Logging now uses log package across the board and truncate logs is fixed

- account/assets/css/style.css
- account/assets/js/panelHandlers/security/ip_list.js
- account/assets/js/panelHandlers/security/unfilter_ip.js
- account/gPanel.html
- pkg/api/ip/unfilter.go
- pkg/database/ip_filtering.go
- pkg/gpaccount/apihandler.go
- pkg/public/filter.go
- pkg/public/public.go
- pkg/public/servehttp.go
- pkg/public/toggle.go
> Finished IP Filtering Functionality

- pkg/api/user/list.go
- pkg/database/users.go
- pkg/gpserver/apihandler.go
- server/document_root/assets/js/panelHandlers/users/new.js
- server/document_root/assets/js/panelHandlers/users/open.js
- server/document_root/gPanel.html
> Adding new users to server now works in gPanel Server

- pkg/api/user/delete.go
- pkg/api/user/update_password.go
- pkg/database/database.go
- pkg/gpserver/apihandler.go
- server/document_root/assets/js/panelHandlers/users/delete.js
- server/document_root/assets/js/panelHandlers/users/new.js
- server/document_root/assets/js/panelHandlers/users/new_password.js
- server/document_root/assets/js/panelHandlers/users/open.js
- server/document_root/gPanel.html
> Changing passwords and deletion of server users

- pkg/api/bundle/delete.go
- pkg/gpserver/apihandler.go
- server/document_root/assets/js/panelHandlers/bundles/specific/delete.js
- server/document_root/assets/js/panelHandlers/bundles/specific/server/status.js
- server/document_root/gPanel.html
> Bundles can now be deleted from the server

- .gitignore
- pkg/api/bundle/create.go
- pkg/api/settings/get_admin.go
- pkg/api/settings/get_smtp.go
- pkg/api/settings/set_admin.go
- pkg/api/settings/set_smtp.go
- pkg/database/settings.go
- pkg/gpserver/apihandler.go
- server/document_root/assets/js/panelHandlers/settings/admin.js
- server/document_root/assets/js/panelHandlers/settings/smtp.js
- server/document_root/gPanel.html
> Secure account credentials, track a server admin email/name for use in auto-generated emails to clients

- pkg/gpaccount/servehttp.go
- pkg/gpserver/servehttp.go
> Redirect already authenticated users away from the login page

- account/assets/js/panelHandlers/domains_subdomains/domain_management.js
- account/gPanel.html
- main.go
- pkg/api/bundle/create.go
- pkg/api/bundle/delete.go
- pkg/api/domain/link.go
- pkg/api/domain/unlink.go
- pkg/api/settings/add_nameserver.go
- pkg/api/settings/get_admin.go
- pkg/api/settings/get_nameservers.go
- pkg/api/settings/remove_nameserver.go
- pkg/api/settings/set_admin.go
- pkg/api/settings/set_smtp.go
- pkg/database/database.go
- pkg/database/domains.go
- pkg/gpaccount/apihandler.go
- pkg/gpaccount/toggle.go
- pkg/gpserver/apihandler.go
- pkg/public/toggle.go
- pkg/router/router.go
- server/document_root/assets/js/panelHandlers/settings/add_nameserver.js
- server/document_root/assets/js/panelHandlers/settings/nameserver_config.js
- server/document_root/assets/js/panelHandlers/settings/remove_nameserver.js
- server/document_root/assets/js/panelHandlers/users/open.js
- server/document_root/gPanel.html
> Routing done, nameserver configuration done, continued work on domain manager

- pkg/database/domains.go
- pkg/gpserver/apihandler.go
- server/document_root/assets/js/panelHandlers/settings/client_domains.js
- server/document_root/gPanel.html
Referencing issues #110 and #111
> Fixed bundle deletion hangup and added support for domain view/deletion from server

- pkg/public/servehttp.go
> public can now serve php files

- pkg/public/servehttp.go
> php-cgi instead of php

- README.md
- account/assets/js/init.js
- account/assets/js/panelHandlers/users/addkey.js
- account/assets/js/panelHandlers/users/deletekey.js
- account/assets/js/panelHandlers/users/getkeys.js
- account/gPanel.html
- pkg/api/bundle/delete.go
- pkg/api/ssh/getkeys.go
- pkg/gpaccount/apihandler.go
- pkg/system/keys.go
Final PR to consider issue #120 completely done for the time being. FTP will come later.
> Frontend SSH interface and user deletion upon bundle deletion

- account/assets/js/panelHandlers/domains_subdomains/subdomain_add.js
- account/assets/js/panelHandlers/domains_subdomains/subdomain_management.js
- account/assets/js/panelHandlers/domains_subdomains/subdomain_remove.js
- account/gPanel.html
- pkg/api/subdomain/add.go
- pkg/api/subdomain/list.go
- pkg/api/subdomain/remove.go
- pkg/database/database.go
- pkg/database/subdomains.go
- pkg/gpaccount/apihandler.go
- pkg/gpaccount/gpaccount.go
- pkg/gpserver/servehttp.go
- pkg/public/public.go
- pkg/public/servehttp.go
- pkg/router/router.go
Domain router had a few issues that would cause the indexing to freak out and I fixed those as well as routed unknown requests to a 400 bad request page supplied by the server.
Subdomain implementation references issue #121
> Fixed domain router issues and implemented subdomains

- pkg/api/user/register.go
I added a check for password input of 8 characters minimum.
In respect to the issue #125.
> password length (>=8)
